C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.1.3)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraprow_prod (row_prodf2pywrap, i, j, ia, ja,
     & ra, w)
      external row_prod
      integer i
      integer j
      integer ia(*)
      integer ja(*)
      real ra(*)
      real w(*)
      real row_prodf2pywrap
      real  row_prod
      row_prodf2pywrap = row_prod(i, j, ia, ja, ra, w)
      end


      subroutine f2pywrapdot (dotf2pywrap, x, y, mx, my, nx, ny, w
     &)
      external dot
      integer nx
      integer ny
      real x(*)
      real y(*)
      integer mx(*)
      integer my(*)
      real w(*)
      real dotf2pywrap
      real  dot
      dotf2pywrap = dot(x, y, mx, my, nx, ny, w)
      end


      subroutine f2pywrapdev2 (dev2f2pywrap, n, w, y, p, pmin)
      external dev2
      integer n
      real pmin
      real w(n)
      real y(n)
      real p(n)
      real dev2f2pywrap
      real  dev2
      dev2f2pywrap = dev2(n, w, y, p, pmin)
      end


      subroutine f2pywrapazero (azerof2pywrap, n, y, g, q, jerr)
      external azero
      integer n
      integer jerr
      real y(n)
      real g(n)
      real q(n)
      real azerof2pywrap
      real  azero
      azerof2pywrap = azero(n, y, g, q, jerr)
      end


      subroutine f2pywrapelc (elcf2pywrap, parm, n, cl, a, m)
      external elc
      real parm
      integer n
      real cl(2)
      real a(n)
      integer m(n)
      real elcf2pywrap
      real  elc
      elcf2pywrap = elc(parm, n, cl, a, m)
      end


      subroutine f2pywrapnintot (nintotf2pywrap, ni, nx, nc, a, m,
     & nin, is)
      external nintot
      integer ni
      integer nx
      integer nc
      integer nin
      real a(nx,nc)
      integer m(nx)
      integer is(ni)
      integer nintotf2pywrap
      integer  nintot
      nintotf2pywrap = nintot(ni, nx, nc, a, m, nin, is)
      end


      subroutine f2pywraprisk (riskf2pywrap, no, ni, nk, d, dk, f,
     & e, kp, jp, u)
      external risk
      integer no
      integer ni
      integer nk
      real d(no)
      real dk(nk)
      real f(no)
      real e(no)
      integer kp(nk)
      integer jp(no)
      real u(nk)
      real riskf2pywrap
      real  risk
      riskf2pywrap = risk(no, ni, nk, d, dk, f, e, kp, jp, u)
      end


      subroutine f2pywrapnonzero (nonzerof2pywrap, n, v)
      external nonzero
      integer n
      real v(n)
      integer nonzerof2pywrap
      integer  nonzero
      nonzerof2pywrap = nonzero(n, v)
      end


      subroutine f2pywrapbnorm (bnormf2pywrap, b0, al1p, al2p, g, 
     &usq, jerr)
      external bnorm
      real b0
      real al1p
      real al2p
      real g
      real usq
      integer jerr
      real bnormf2pywrap
      real  bnorm
      bnormf2pywrap = bnorm(b0, al1p, al2p, g, usq, jerr)
      end

